### ISSUE TITLE
Shader compile error X4568 - Invalid parameter txc

### ISSUE THREAD

**Issue by bobmarkinson** [grebord/Fast-Adaptive-AA#1]
Hello Grebord,

I'm seeing this error when trying to use your shader with Reshade version '4.9.1.1003' in DX10:

reshade-shaders\Shaders\FAAA.fx(349, 1): error X4568: 'FXAAPS': input parameter 'txc' interpolation qualifiers do not match vertex shader ones

This error also happens with your LXAA shader.

Hope you can help. :)
Thank you!

**Comment by grebord** [comment]
Hi! Thanks for the feedback! These shaders still need to be updated for current versions of Reshade -should've said that in the readme- I think I'll have some time later in the day to do it.

**Comment by grebord** [comment]
Done, it was a minor thing, it should be working now. Let me know if it's all ok on your end.

**Comment by bobmarkinson** [comment]
All is working well now with both FAAA and LXAA. Thank you for your quick solution!
